# Generated by Django 5.2.1 on 2026-04-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_loanoperation_bhu_aadhar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='relative_info',
        ),
        migrations.AddField(
            model_name='customuser',
            name='aadhar_number',
            field=models.CharField(blank=True, default='', help_text='12-digit Aadhaar number (format: XXXX XXXX XXXX)', max_length=12, verbose_name='Aadhaar Number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Active'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan_number',
            field=models.CharField(blank=True, default='', help_text='10-character PAN (e.g. ABCDE1234F)', max_length=10, verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='10-digit mobile number (mandatory for Agents)', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='loanoperation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
