# Generated by Django 5.2.1 on 2026-04-23 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_customuser_relative_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SROState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='State Name')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='operationhistory',
            name='snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanoperation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='loanoperation',
            name='bhu_aadhar',
            field=models.CharField(blank=True, help_text='14-character alphanumeric Unique Land Parcel Identification Number.', max_length=14, null=True, verbose_name='Bhu Aadhar (ULPIN)'),
        ),
        migrations.AlterField(
            model_name='loanoperation',
            name='doc_attornment',
            field=models.FileField(blank=True, help_text='Letter of Attornment', null=True, upload_to='bank_docs/'),
        ),
        migrations.AlterField(
            model_name='loanoperation',
            name='doc_building_plan',
            field=models.FileField(blank=True, help_text='Approved Building Plan / Sanction Plan', null=True, upload_to='bank_docs/'),
        ),
        migrations.AlterField(
            model_name='loanoperation',
            name='doc_encumbrance',
            field=models.FileField(blank=True, help_text='Encumbrance Certificate (EC) — 13–30 year period', null=True, upload_to='bank_docs/'),
        ),
        migrations.AlterField(
            model_name='loanoperation',
            name='doc_lease_deed',
            field=models.FileField(blank=True, help_text='Registered Lease Deed/Agreement', null=True, upload_to='bank_docs/'),
        ),
        migrations.AlterField(
            model_name='loanoperation',
            name='doc_mother_deed',
            field=models.FileField(blank=True, help_text='Chain of Documents (Mother Deed)', null=True, upload_to='bank_docs/'),
        ),
        migrations.AlterField(
            model_name='loanoperation',
            name='doc_occupancy',
            field=models.FileField(blank=True, help_text='Occupancy Certificate / Completion Certificate', null=True, upload_to='bank_docs/'),
        ),
        migrations.AlterField(
            model_name='loanoperation',
            name='doc_tax_receipts',
            field=models.FileField(blank=True, help_text='Latest Property Tax Receipts', null=True, upload_to='bank_docs/'),
        ),
        migrations.AlterField(
            model_name='loanoperation',
            name='doc_title_deed',
            field=models.FileField(blank=True, help_text='Original Title Deeds (Sale Deed/Conveyance Deed)', null=True, upload_to='bank_docs/'),
        ),
        migrations.CreateModel(
            name='SRODistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='District Name')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.srostate')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['name'],
                'unique_together': {('state', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SROSubDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sub-District Name')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_districts', to='core.srodistrict')),
            ],
            options={
                'verbose_name': 'Sub-District',
                'verbose_name_plural': 'Sub-Districts',
                'ordering': ['name'],
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SROOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sro_code', models.CharField(max_length=50, unique=True, verbose_name='SRO Code')),
                ('sro_name', models.CharField(blank=True, max_length=200, verbose_name='SRO Name')),
                ('sub_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='core.srosubdistrict')),
            ],
            options={
                'verbose_name': 'SRO Office',
                'verbose_name_plural': 'SRO Offices',
                'ordering': ['sro_code'],
            },
        ),
    ]
